---
- name: configure nginx repository
  yum_repository:
    name: nginx
    description: nginx stable repo
    baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
    gpgkey: https://nginx.org/keys/nginx_signing.key
    gpgcheck: yes
    enabled: yes

- name: install nginx
  yum: name=nginx state=present

- name: start and enables nginx service
  systemd: name=nginx state=started enabled=yes

- name: copy nginx config file
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: reload_nginx

- name: remove default nginx vhost config file
  file: name=/etc/nginx/conf.d/default.conf state=absent
  notify: reload_nginx

- name: copy vhost config file
  template:
    src: vhost.conf.j2
    dest: /etc/nginx/conf.d/vhost.conf
    owner: root
    group: root
    mode: 0644
  notify: reload_nginx
